version: 0.2

env:
  variables:
    CI: true
    REGION: ap-southeast-2
    WEBSITE_BUCKET: s3://techradarstaticsitestack-staticsitebucket8958ee3f-6fmeuqatxkuq/

phases:
  pre_build:
    commands:
      - cd app
      - npm i
      - npm test

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - rm -rf coverage
      - aws s3 cp ./build/ $WEBSITE_BUCKET --recursive --acl private
