version: 0.2

env:
  variables:
    CI: true
    REGION: ap-southeast-2

phases:
  pre_build:
    commands:
      - cd aws
      - npm i
      - npm test -- -u

  build:
    commands:
      - npm run deploy
