Resources:
  CodePipelineArtifactsBucketF1E925CF:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: TechRadarDevToolsStack/CodePipeline/ArtifactsBucket/Resource
  CodePipelineRoleB3A660B4:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: TechRadarDevToolsStack/CodePipeline/Role/Resource
  CodePipelineRoleDefaultPolicy8D520A8D:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
              - s3:DeleteObject*
              - s3:PutObject*
              - s3:Abort*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - CodePipelineArtifactsBucketF1E925CF
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - CodePipelineArtifactsBucketF1E925CF
                        - Arn
                    - /*
          - Action:
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
              - codebuild:StopBuild
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - DeployInfra12589F88
                - Arn
          - Action:
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
              - codebuild:StopBuild
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - BuildAndTestB9A2F419
                - Arn
          - Action:
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
              - codebuild:StopBuild
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - DeployToProd5A783BE8
                - Arn
        Version: "2012-10-17"
      PolicyName: CodePipelineRoleDefaultPolicy8D520A8D
      Roles:
        - Ref: CodePipelineRoleB3A660B4
    Metadata:
      aws:cdk:path: TechRadarDevToolsStack/CodePipeline/Role/DefaultPolicy/Resource
  CodePipelineB74E5936:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn:
        Fn::GetAtt:
          - CodePipelineRoleB3A660B4
          - Arn
      Stages:
        - Actions:
            - ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              Configuration:
                Owner: MechanicalRock
                Repo: tech-radar
                Branch: master
                OAuthToken:
                  Ref: GitHubOAuthTokenParameter6FA15971
                PollForSourceChanges: false
              InputArtifacts:
                []
              Name: GitHub_Source
              OutputArtifacts:
                - Name: Artifact_TechRadarDevToolsStackGitHubSourceA49F284D
              RunOrder: 1
          Name: SourceStage
        - Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName:
                  Ref: DeployInfra12589F88
              InputArtifacts:
                - Name: Artifact_TechRadarDevToolsStackGitHubSourceA49F284D
              Name: DeployInfraAction
              OutputArtifacts:
                - Name: Artifact_TechRadarDevToolsStackDeployInfraAction1B42F1C0
              RunOrder: 1
          Name: InfraStage
        - Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName:
                  Ref: BuildAndTestB9A2F419
              InputArtifacts:
                - Name: Artifact_TechRadarDevToolsStackDeployInfraAction1B42F1C0
              Name: BuildAndTestAction
              OutputArtifacts:
                - Name: Artifact_TechRadarDevToolsStackBuildAndTestActionBAF5B445
              RunOrder: 1
          Name: DevStage
        - Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName:
                  Ref: DeployToProd5A783BE8
              InputArtifacts:
                - Name: Artifact_TechRadarDevToolsStackBuildAndTestActionBAF5B445
              Name: prodDeployAction
              OutputArtifacts:
                - Name: Artifact_TechRadarDevToolsStackprodDeployActionE117DD81
              RunOrder: 1
          Name: ProdStage
      ArtifactStore:
        Location:
          Ref: CodePipelineArtifactsBucketF1E925CF
        Type: S3
      Name: code-pipeline
      RestartExecutionOnUpdate: true
    DependsOn:
      - CodePipelineRoleB3A660B4
      - CodePipelineRoleDefaultPolicy8D520A8D
    Metadata:
      aws:cdk:path: TechRadarDevToolsStack/CodePipeline/Resource
  CodeBuildRole728CBADE:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
    Metadata:
      aws:cdk:path: TechRadarDevToolsStack/CodeBuildRole/Resource
  CodeBuildRoleDefaultPolicy829527DE:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: DeployInfra12589F88
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: DeployInfra12589F88
                    - :*
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
              - s3:DeleteObject*
              - s3:PutObject*
              - s3:Abort*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - CodePipelineArtifactsBucketF1E925CF
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - CodePipelineArtifactsBucketF1E925CF
                        - Arn
                    - /*
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: BuildAndTestB9A2F419
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: BuildAndTestB9A2F419
                    - :*
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
              - s3:DeleteObject*
              - s3:PutObject*
              - s3:Abort*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - CodePipelineArtifactsBucketF1E925CF
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - CodePipelineArtifactsBucketF1E925CF
                        - Arn
                    - /*
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: DeployToProd5A783BE8
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: DeployToProd5A783BE8
                    - :*
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
              - s3:DeleteObject*
              - s3:PutObject*
              - s3:Abort*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - CodePipelineArtifactsBucketF1E925CF
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - CodePipelineArtifactsBucketF1E925CF
                        - Arn
                    - /*
        Version: "2012-10-17"
      PolicyName: CodeBuildRoleDefaultPolicy829527DE
      Roles:
        - Ref: CodeBuildRole728CBADE
    Metadata:
      aws:cdk:path: TechRadarDevToolsStack/CodeBuildRole/DefaultPolicy/Resource
  GitHubSourceWebhookResourceB32EADBE:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken:
          Ref: GitHubOAuthTokenParameter6FA15971
      Filters:
        - JsonPath: $.ref
          MatchEquals: refs/heads/{Branch}
      TargetAction: GitHub_Source
      TargetPipeline:
        Ref: CodePipelineB74E5936
      TargetPipelineVersion: 1
      RegisterWithThirdParty: true
    Metadata:
      aws:cdk:path: TechRadarDevToolsStack/GitHub_Source/WebhookResource
  DeployInfra12589F88:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/nodejs:10.1.0
        PrivilegedMode: false
        Type: LINUX_CONTAINER
      ServiceRole:
        Fn::GetAtt:
          - CodeBuildRole728CBADE
          - Arn
      Source:
        Type: CODEPIPELINE
    Metadata:
      aws:cdk:path: TechRadarDevToolsStack/DeployInfra/Resource
  BuildAndTestB9A2F419:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/nodejs:10.1.0
        PrivilegedMode: false
        Type: LINUX_CONTAINER
      ServiceRole:
        Fn::GetAtt:
          - CodeBuildRole728CBADE
          - Arn
      Source:
        BuildSpec: aws/buildspec.yml
        Type: CODEPIPELINE
    Metadata:
      aws:cdk:path: TechRadarDevToolsStack/BuildAndTest/Resource
  DeployToProd5A783BE8:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/nodejs:10.1.0
        PrivilegedMode: false
        Type: LINUX_CONTAINER
      ServiceRole:
        Fn::GetAtt:
          - CodeBuildRole728CBADE
          - Arn
      Source:
        Type: CODEPIPELINE
    Metadata:
      aws:cdk:path: TechRadarDevToolsStack/DeployToProd/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=0.22.0,@aws-cdk/assets=0.22.0,@aws-cdk/assets-docker=0.22.0,@aws-cdk/aws-cloudformation=0.22.0,@aws-cdk/aws-cloudfront=0.22.0,@aws-cdk/aws-cloudwatch=0.22.0,@aws-cdk/aws-codebuild=0.22.0,@aws-cdk/aws-codepipeline=0.22.0,@aws-cdk/aws-codepipeline-api=0.22.0,@aws-cdk/aws-ec2=0.22.0,@aws-cdk/aws-ecr=0.22.0,@aws-cdk/aws-events=0.22.0,@aws-cdk/aws-iam=0.22.0,@aws-cdk/aws-kms=0.22.0,@aws-cdk/aws-lambda=0.22.0,@aws-cdk/aws-route53=0.22.0,@aws-cdk/aws-s3=0.22.0,@aws-cdk/aws-s3-notifications=0.22.0,@aws-cdk/aws-sns=0.22.0,@aws-cdk/aws-sqs=0.22.0,@aws-cdk/cdk=0.22.0,@aws-cdk/cx-api=0.22.0,jsii-runtime=node.js/v10.13.0
Parameters:
  GitHubOAuthTokenParameter6FA15971:
    Type: AWS::SSM::Parameter::Value<String>
    Default: github-oauth-token
    NoEcho: true

